name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login
      uses: docker/login-action@v2
      with:
        username: masteroz
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push API Gateway
      uses: docker/build-push-action@v4
      with:
        context: ./Cafe_Management_System/api-gateway
        push: true
        tags: masteroz/cafe-api-gateway:latest
        
    - name: Build and push Menu Service
      uses: docker/build-push-action@v4
      with:
        context: ./Cafe_Management_System/menu-services
        push: true
        tags: masteroz/cafe-menu-service:latest
        
    - name: Build and push Order Service
      uses: docker/build-push-action@v4
      with:
        context: ./Cafe_Management_System/order-services
        push: true
        tags: masteroz/cafe-order-service:latest
        
    - name: Build and push Payment Service
      uses: docker/build-push-action@v4
      with:
        context: ./Cafe_Management_System/payment-services
        push: true
        tags: masteroz/cafe-payment-service:latest
        
    - name: Build and push Inventory Service
      uses: docker/build-push-action@v4
      with:
        context: ./Cafe_Management_System/inventory-services
        push: true
        tags: masteroz/cafe-inventory-service:latest
        
    - name: Build and push Customer Service
      uses: docker/build-push-action@v4
      with:
        context: ./Cafe_Management_System/customer-services
        push: true
        tags: masteroz/cafe-customer-service:latest

